# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('month', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('schedule', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('crew', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsschedule.Team'),
        ),
    ]
