# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsschedule', '0003_auto_20160523_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
