# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsschedule', '0004_auto_20160523_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.CharField(choices=[('styczeń', 'styczeń'), ('luty', 'luty'), ('marzec', 'marzec'), ('kwiecień', 'kwiecień'), ('maj', 'maj'), ('czerwiec', 'czerwiec'), ('lipiec', 'lipiec'), ('sierpień', 'sierpień'), ('wrzesień', 'wrzesień'), ('październik', 'październik'), ('listopad', 'listopad'), ('grudzień', 'grudzień')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=20),
        ),
    ]
