# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsschedule', '0005_auto_20160523_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='letsschedule.User'),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='letsschedule.User'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='crew',
        ),
        migrations.AddField(
            model_name='team',
            name='crew',
            field=models.ManyToManyField(to='letsschedule.Person'),
        ),
    ]
