# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsschedule', '0007_auto_20160524_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='crew',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letsschedule.Team'),
        ),
    ]
