# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='akey_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 19, 29, 57, 661712, tzinfo=utc)),
        ),
    ]
