# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20160713_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='akey_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 26, 19, 47, 34, 185053, tzinfo=utc)),
        ),
    ]
