# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_auto_20160724_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='akey_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 26, 19, 53, 20, 450651, tzinfo=utc)),
        ),
    ]
